
import { PromptSection } from '@/types/promptService';
import { BaseSectionsService } from './baseSectionsService';

export class TemplateService extends BaseSectionsService {
  async updateMarkdownTemplate(moduleType: string = 'post_secondary'): Promise<PromptSection> {
    const templateKey = moduleType === 'k12' ? 'markdown_report_template_k12' : 'markdown_report_template_post_secondary';
    
    const newMarkdownTemplate = `# Disability Accommodation Report

**Case Information:**
- Assessment Date: [Date]
- Evaluator: [Name]
- Institution: [Institution Name]
- Module Type: ${moduleType === 'k12' ? 'K-12 Education' : 'Post-Secondary Education'}

## 2. Functional Impact Summary

**Observed Barrier 1:** [First functional barrier description]  
**Evidence:** [Supporting evidence with specific test scores and citations]

**Observed Barrier 2:** [Second functional barrier description]  
**Evidence:** [Supporting evidence with specific test scores and citations]

[Continue numbering sequentially for all barriers identified (1, 2, 3, etc.)]

## 3. Accommodation & Support Plan

### 3.1 Academic Accommodations
1. [First academic accommodation with detailed description]
2. [Second academic accommodation with detailed description]
3. [Additional academic accommodations as needed]

### 3.2 Instructional / Program Accommodations
1. [First instructional accommodation with detailed description]
2. [Second instructional accommodation with detailed description]
3. [Additional instructional accommodations as needed]

### 3.3 Auxiliary Aids & Services
1. [First auxiliary aid with detailed description]
2. [Second auxiliary aid with detailed description]
3. [Additional auxiliary aids as needed]

### 3.4 Non-Accommodation Supports / Referrals
1. [First support service with detailed description]
2. [Second support service with detailed description]
3. [Additional support services as needed]

## 4. QC Summary
[Quality control summary and validation notes]

---
*Report generated by AI Analysis System with Sequential Numbering*`;

    return this.savePromptSection(templateKey, newMarkdownTemplate, undefined, undefined, moduleType);
  }

  async updateTemplateWithQCSection(moduleType: string = 'post_secondary'): Promise<PromptSection> {
    const templateKey = moduleType === 'k12' ? 'markdown_report_template_qc_k12' : 'markdown_report_template_qc_post_secondary';
    
    const enhancedTemplate = `# Disability Accommodation Report

**Case Information:**
- Assessment Date: [Date]
- Evaluator: [Name]
- Institution: [Institution Name]
- Module Type: ${moduleType === 'k12' ? 'K-12 Education' : 'Post-Secondary Education'}

## 2. Functional Impact Summary

### Identified Barriers
[List functional barriers identified from documentation analysis]

### Academic Impact
[Describe how barriers affect academic performance and participation]

## 3. Accommodation & Support Plan

### 3.1 Academic Accommodations
[List specific academic accommodations recommended]

### 3.2 Instructional / Program Accommodations  
[List instructional or program modifications]

### 3.3 Auxiliary Aids & Services
[List auxiliary aids and assistive services]

### 3.4 Non-Accommodation Supports / Referrals
[List additional supports and referral recommendations]

## 4. Quality Control Summary

### Validation Results
- **Barriers Validated:** [Number/List]
- **Evidence Quality:** [Assessment]
- **Accommodation Compliance:** [Status]

### Review Notes
[Any additional quality control observations]

### Confidence Level
- **Overall Confidence:** [High/Medium/Low]
- **Areas Requiring Review:** [List if any]

---
*Report generated by AI Analysis System with Enhanced QC*`;

    return this.savePromptSection(templateKey, enhancedTemplate, undefined, undefined, moduleType);
  }
}
